### ISSUE TITLE
Validation with array of objects doesn't work.

### ISSUE THREAD

**Issue by testgit-1** [dwightjack/vue-types#42] opened 2018-11-06 13:54 UTC
Case: an array of objects with a specific structure.
In react we can use
```
   arrayWithShape: PropTypes.arrayOf(PropTypes.shape({
     color: PropTypes.string.isRequired,
     fontSize: PropTypes.number.isRequired,
   })),
```

In Vue similar code does not work.
```
'projects': VueTypes.arrayOf(VueTypes.shape({
        'title': VueTypes.string.isRequired,
        'workDurationType': VueTypes.oneOf(['few_months', 'few_weeks', 'one_time', 'long_term', 'finding_out',]),
})),
```

**Comment by dwightjack** [comment] 2018-11-07 01:30
Hi,

I've tested the described prop type but I'm unable to reproduce the error. Here is my test bin: https://jsbin.com/budequv/edit?html,js,console,output

Could you provide some more details on your scenario?

Thanks!

**Comment by dwightjack** [comment] 2018-12-12 08:45
Hi,

I'm closing this for now. Feel free to reopen the issue or to open another one if you experience any further problem.

**Closed by dwightjack** 2018-12-12 08:45 UTC
