### ISSUE TITLE
Hello, why does undefineProps return unknown when defined?

### ISSUE THREAD

**Issue by Evllis** [dwightjack/vue-types#449] opened 2024-01-10 09:31 UTC
**Library version**

![image](https://github.com/dwightjack/vue-types/assets/13903944/e2c6d309-6be4-406d-b66b-375910ebcc0c)

**Vue.js version**

![image](https://github.com/dwightjack/vue-types/assets/13903944/a9c3d6fa-73bd-4c9c-b0de-d1cfac8d27ef)

**Question**

![20240110_172008](https://github.com/dwightjack/vue-types/assets/13903944/934fe224-3277-49a5-ae62-64bab65a7641)

![20240110_171957](https://github.com/dwightjack/vue-types/assets/13903944/27ff3722-2841-4d09-a30f-feda6890ad34)

![20240110_171936](https://github.com/dwightjack/vue-types/assets/13903944/d7fc1a33-853a-43c4-9f84-d27bbff2eacd)

![20240110_171914](https://github.com/dwightjack/vue-types/assets/13903944/c40fcae6-e4b9-4ded-811c-28a51ad59474)

![20240110_171856](https://github.com/dwightjack/vue-types/assets/13903944/b629d019-1e0a-4964-8139-4e7242daf323)

I searched on Google for a long time but couldn't find a solution to the problem

Looking at the code prompt, the methods all return results, but when declaring variables, the properties are all unknown. I don't know why Can you help me, thank you.

![20240110_172905](https://github.com/dwightjack/vue-types/assets/13903944/9c5a262b-ada1-48ba-bb97-a48f8a21f8fb)

But when I use the original notation, I can access the target type, but I don't want to do this because compared to your plugin, this notation is too cumbersome

**Comment by dwightjack** [comment] 2024-01-12 02:42
Hello, I tried to create a reproduction demo here: https://github.com/dwightjack/vitejs-vite-pktjcl. When I open the [HelloWorld.vue](https://github.com/dwightjack/vitejs-vite-pktjcl/blob/0c72d9e95713ac7242e3d48302a1689ec474b75d/src/components/HelloWorld.vue) component in VSCode I see the correct type:

<img width="318" alt="image" src="https://github.com/dwightjack/vue-types/assets/104721/ba91e46f-5fd0-4456-9c39-c1c7f665f1d6">

Could you try to download it, install it (`npm ci`), and let me know if you see the correct typing as well?

**Comment by Evllis** [comment] 2024-01-15 01:18
Okay, thank you. I'll give it a try and let you know once I have the results.

**Comment by Evllis** [comment] 2024-01-15 01:23
![image](https://github.com/dwightjack/vue-types/assets/13903944/41625918-ef27-4e5b-ab7c-ea11368ddf09)

I just downloaded your demo and installed it, and I have correctly displayed the type here.

It seems that there is an issue with the configuration of my project, which affects the correct derivation of vue types.

Let me find out where the problem is.

Anyway, thank you for your help, thank you very much.

**Comment by hls-1992** [comment] 2024-04-17 07:10
May I ask if you have identified the problem which cause the type was inferred to be unknown,
I have the same question

**Comment by hls-1992** [comment] 2024-04-17 08:15
I have the same question
I think it was caused by the TS option 'strictNullChecks": false'
when I delete this row and restart vscode,the question is missing

**Comment by dwightjack** [comment] 2024-11-20 00:36
I'll close this issue for now. Feel free to re open it if the problem pops-up again.

**Closed by dwightjack** 2024-11-20 00:36 UTC
Labels: question
